/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/github.glb 
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-github-logo-441d03d1076b44f483df551e02d970fe
Title: 3D Github Logo
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Github(props) {
  const { nodes, materials } = useGLTF('models/github.glb')
  const [isHovered, setIsHovered] = useState(false);
  const group = useRef();
  const originalRotation = useRef([Math.PI / 2, 0, 0]);
  const rotationSpeed = 0.2;
  
  useEffect(() => {
    if (group.current) {
      originalRotation.current = [...group.current.rotation];
    }
  }, []);

  useFrame(() => {
    if (isHovered) {
      group.current.rotateY(rotationSpeed);
    } else {
      group.current.rotation.y += (originalRotation.current[1] - group.current.rotation.y) * 0.1;
    }
  });

  return (
    <group onPointerEnter={(e) => setIsHovered(true)} onPointerLeave={(e) => setIsHovered(false)} ref={group} {...props} dispose={null}>
      <group position={props.position} rotation={[Math.PI / 2, 0, 0]} scale={16}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.glossy_putih} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.github} />
      </group>
    </group>
  )
}

useGLTF.preload('models/github.glb')
